GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjE1OTk0NjcsImV4cCI6MTYyMTU5OTQ4MiwiYXVkIjoiNjBhNzdjN2UxYWJiNzkyZTdjZmVlZjJiIiwiaXNzIjoiZmFjZWJvb2suY29tIn0.M5hHkyPoH4c_5bbXzfvzh6ViIgKC2nUI9uZO-8_Kz-c

###
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "vkn110072@gmail.com",
  "password": "123456"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "vkn110172@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3000/auth/refresh-token

###
DELETE  http://localhost:3000/auth/logout

